apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
 name: ratings-auth
 namespace: bookinfo-backends
spec:
 selector:
   matchLabels:
     app: ratings
 action: ALLOW
 rules:
 - from:
   - source:
       principals:
       - '*/ns/bookinfo-backends/sa/bookinfo-reviews'