apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: reviews-auth
  namespace: bookinfo-backends
spec:
  selector:
    matchLabels:
      app: reviews
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - "*/ns/bookinfo-frontends/sa/bookinfo-productpage"
